name: flax
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - anyio=3.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.5
  - chardet=4.0.0
  - chex=0.0.7
  - contextvars=2.4
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dataclasses=0.8
  - decorator=4.4.2
  - defusedxml=0.7.1
  - dm-tree=0.1.5
  - entrypoints=0.3
  - ffmpeg=4.3
  - flax=0.3.4
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - idna=2.10
  - immutables=0.15
  - importlib-metadata=4.3.1
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jax=0.2.13
  - jaxlib=0.1.67
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.5.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.41.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - msgpack-python=1.0.2
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.6
  - ninja=1.10.2
  - notebook=6.3.0
  - numpy=1.19.5
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - optax=0.0.6
  - packaging=20.9
  - pandoc=2.13
  - pandocfilters=1.4.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-flatbuffers=2.0
  - python_abi=3.6
  - pytorch=1.8.1
  - pytz=2021.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.25.1
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.5
  - terminado=0.10.0
  - testpath=0.5.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - jedi==0.17.2
    - parso==0.7.1

